apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole-kubernetes
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: '2.15.0'
      sourceRef:
        kind: HelmRepository
        name: pihole-kubernetes
        namespace: pihole
      interval: 1m
  values:
    serviceWeb:
      type: NodePort 