apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole-kubernetes
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      chart: pihole
      version: '2.15.0'
      sourceRef:
        kind: HelmRepository
        name: pihole-kubernetes
        namespace: pihole
      interval: 1m
  values:
    serviceDns:
      loadBalancerIP: 192.168.1.110
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer