apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  annotations:
    metallb.universe.tf/address-pool: first-pool
  labels:
    app: homeassistant
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.111
  ports:
    - name: "8123"
      port: 8123
      targetPort: 8123
  selector:
    app: homeassistant