kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homeassistant-pvc
  namespace: homeassistant
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
