apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  type: LoadBalancer
  ports:
    - name: "8123"
      port: 8123
      targetPort: 8123
  selector:
    app: homeassistant