kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: homeassistant-pvc
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
